### ISSUE TITLE
Criar tela principal do aplicativo android

### ISSUE THREAD

**Issue by rodrigocam** [rodrigocam/gold-penny-app#1]
A tela principal do aplicativo deve mostrar os produtos, disponíveis no cardápio do evento, com a opção de adicioná los ao pedido. Esta tela também deve possuir a opção finalizar pedido, a qual enviará o comando para imprimir as fichas. Esta tela deve ser elaborada de forma que no futuro consigamos enviar requisições para nosso servidor com os produtos vendidos.

**Comment by pablodiegoss** [comment]
Na seleção de produtos é importante lembrar de campos como "quantidade" e talvez alguma categorização que facilite a seleção dos produtos. Fechando um pedido completo com vários itens antes de mandar a requisição de impressão
