### ISSUE TITLE
Criar pacote de interface de comunicação com a impressora

### ISSUE THREAD

**Issue by rodrigocam** [rodrigocam/gold-penny-app#2]
Este pacote deve conter métodos em alto nível para facilitar a montagem das fichas de produtos, portanto este pacote será nossa camada mediadora entre a linguagem Java e comandos ESC/POS.

**Comment by pablodiegoss** [comment]
A transformação de string em ESC/POS é mais interessante implementarmos do 0 ou tentar empacotar o lib que já encontramos de conversão?

**Comment by rodrigocam** [comment]
Podemos fazer um fork e alterar o que for necessário, a lib também implementa um módulo de saída serial, que talvez não seja útil para nossa aplicação. Segue o link da lib e um link de um guia de ESC/POS. [ESC/POS-LIB](https://github.com/TerryTsai/EscPos),  [ESC/POS-GUIDE](http://download.brother.com/welcome/docp000579/cv_td4000_eng_escp_120.pdf)
